# No scene or resource may hold a reference that resolves to nothing -- graded in both of the
# forms Godot writes one: the uid half (#240 follow-up) below, and the path half (#596) after it.
#
# Godot writes an ext_resource two ways: `path=` alone, or `uid=` PLUS `path=`. When both are
# present the uid wins and the path is only the fallback, so a uid that resolves to nothing --
# or to a DIFFERENT file -- still loads correctly today and prints a warning. That warning is the
# entire symptom, which is why two of them survived for months: Battle3D.tscn pointed at a
# MeshLibrary uid nothing claimed, and SteamRune.tres at a TransmutationData uid nothing claimed.
# Both were noise until the day the target moves, at which point the fallback path breaks too and
# the reference resolves to the wrong file or to nothing at all.
#
# It is a repo law rather than a fix because the two instances had unrelated causes and neither
# was authored by hand: `lookdev_meshlib.tres` is REGENERATED by tools/lookdev/gen_lookdev_assets.gd
# through a plain ResourceSaver.save(), which writes no uid, while the scene kept the uid it had
# been stamped with earlier. Anything that rewrites a .tres outside the editor can do this again.
#
# The question is asked of ResourceUID, the engine's own registry -- deliberately NOT by parsing
# the target's header, which would be a second answer to "what uid does this file have" and free
# to disagree with the one Godot uses at load time.
extends GdUnitTestSuite

# The project's own content, which is not only the three content folders: Classes/dev/AttackTypeToggle.tres
# and tests/support/CastFixture.tres are .tres the project authors too, and a law that says NO reference
# resolves to nothing may not quietly mean "none of the ones in three folders". addons/ is vendored
# (gdUnit4's own files are not ours to fix) and .godot/ is cache.
const SCANNED_ROOTS: Array[String] = ["res://Scenes/", "res://Resources/", "res://Scenarios/",
		"res://Classes/", "res://tests/"]

# A uid= appears only on an ext_resource/sub_resource header line, and both start with '['.
const UID_PREFIX := "uid://"


func test_every_uid_reference_resolves_to_the_file_beside_it() -> void:
	var checked := 0
	var resolved := 0
	for file: String in _scan():
		for ref: Dictionary in _uid_references(file):
			checked += 1
			var uid: String = ref["uid"]
			var path: String = ref["path"]
			var id: int = ResourceUID.text_to_id(uid)
			assert_bool(ResourceUID.has_id(id)).override_failure_message(
				"%s references %s (-> %s), which no file claims. Godot falls back to the path and "
				% [file, uid, path]
				+ "warns; delete the uid= attribute, or give the target a uid."
			).is_true()
			if not ResourceUID.has_id(id):
				continue
			resolved += 1
			assert_str(ResourceUID.get_id_path(id)).override_failure_message(
				"%s references %s beside path %s, but that uid resolves to a DIFFERENT file"
				% [file, uid, path]
			).is_equal(path)

	# Non-vacuity, both halves. Without the first, an empty scan passes this suite while proving
	# nothing (the tests/dev/test_look_presets.gd lesson). Without the second, a ResourceUID that
	# came up empty in a headless run would report every reference as dangling -- the failure would
	# be loud rather than silent, but it would be the SUITE's bug and not the repo's.
	assert_int(checked).override_failure_message(
		"the scan found no uid references at all -- SCANNED_ROOTS is wrong, not the repo"
	).is_greater(0)
	assert_int(resolved).override_failure_message(
		"no uid resolved at all -- ResourceUID is unpopulated in this run, so the failures above "
		+ "are this suite's fault. Re-run after `godot --headless --import`."
	).is_greater(0)


# The sibling law, and the one a content rename breaks (#596). An ext_resource with no uid= is
# path-only, so the case above skips it by construction and NOTHING graded the path itself:
# `356a2e7` deleted two weapon .tres while four files still named them, Level_1 stopped loading,
# and five cases went red in suites two steps from the cause. The tree that authors a rename is
# structurally unable to notice -- the editor holds the old resource in memory and the deleted
# file may still sit there untracked -- so a fresh clone, a worktree and CI are the only places
# the fault is visible at all. That is what makes it a repo law rather than a fix.
#
# Asked of FileAccess, not ResourceLoader: "is a file there" is the entire question, and a loader
# that merely recognises the extension would answer yes for a path resolving to nothing.
func test_every_resource_path_points_at_a_real_file() -> void:
	var checked := 0
	for file: String in _scan():
		for path: String in _reference_paths(file):
			checked += 1
			assert_bool(FileAccess.file_exists(path)).override_failure_message(
				"%s references %s, which no file answers. Deleting or renaming a .tres sweeps "
				% [file, path]
				+ "its referrers IN THE SAME DIFF -- repoint this line, or restore the target."
			).is_true()

	# Scan integrity, not a content claim: the repo always ships scenes, so zero references read
	# means SCANNED_ROOTS or the parser is wrong. An empty CONTENT folder is not a failure here --
	# this law is about references that exist, and no reference is trivially no dangling one.
	assert_int(checked).override_failure_message(
		"the scan found no path references at all -- SCANNED_ROOTS is wrong, not the repo"
	).is_greater(0)


# Every .tscn/.tres under the scanned roots, recursively.
func _scan() -> Array[String]:
	var found: Array[String] = []
	var pending: Array[String] = SCANNED_ROOTS.duplicate()
	while not pending.is_empty():
		var dir_path: String = pending.pop_back()
		var dir := DirAccess.open(dir_path)
		if dir == null:
			continue
		for sub: String in dir.get_directories():
			pending.append(dir_path.path_join(sub) + "/")
		for file: String in dir.get_files():
			if file.ends_with(".tscn") or file.ends_with(".tres"):
				found.append(dir_path.path_join(file))
	return found


# The (uid, path) pairs on this file's resource header lines. Read as TEXT rather than by loading
# the scene: loading resolves the reference, which is the very thing under test.
func _uid_references(file_path: String) -> Array[Dictionary]:
	var refs: Array[Dictionary] = []
	var text := FileAccess.get_file_as_string(file_path)
	for line: String in text.split("\n"):
		if not line.begins_with("[ext_resource") and not line.begins_with("[sub_resource"):
			continue
		var uid := _quoted_after(line, "uid=\"")
		var path := _quoted_after(line, "path=\"")
		if uid == "" or path == "" or not uid.begins_with(UID_PREFIX):
			continue
		refs.append({"uid": uid, "path": path})
	return refs


# Every path= on this file's resource header lines, uid-bearing or not. Deliberately the same text
# read a second time rather than a second walk of the tree: one answer to "what does this file
# reference", two laws grading it.
func _reference_paths(file_path: String) -> Array[String]:
	var paths: Array[String] = []
	var text := FileAccess.get_file_as_string(file_path)
	for line: String in text.split("\n"):
		if not line.begins_with("[ext_resource") and not line.begins_with("[sub_resource"):
			continue
		var path := _quoted_after(line, "path=\"")
		if path == "":
			continue
		paths.append(path)
	return paths


func _quoted_after(line: String, key: String) -> String:
	var start := line.find(key)
	if start < 0:
		return ""
	start += key.length()
	var end := line.find("\"", start)
	if end < 0:
		return ""
	return line.substr(start, end - start)
